events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        server_name localhost;

        client_max_body_size 50M;

        # Depuración - muestra detalles adicionales en logs
        error_log /var/log/nginx/error.log debug;

        location / {
            proxy_pass http://web:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off; 
        }

        # Servir archivos estáticos desde /staticfiles
        location /static/ {
            alias /staticfiles/;
            expires 30d; 
            add_header Cache-Control "public";
            # Añadir esto para ver si los archivos existen
            try_files $uri $uri/ =404;
        }

        # Nueva ubicación para servir directamente archivos de assets desde un volumen adicional
        # location /static/assets/ {
        #     alias /assets/;
        #     expires 30d;
        #     add_header Cache-Control "public";
        # }

        location /media/ {
            alias /mediafiles/;
            expires 30d;
            add_header Cache-Control "public";
        }
    }
}